# Hvorfor denne boka? {.unnumbered}

> The ability to take that data, to be able to understand it, to process it, to extract values from it, to visualize it, to communicate it - that's going to be a hugely important skill in the next decades... (@varianHalVarianExplains2009, Chief Economist Google og Professor Emeritus University of California, Berkeley)

Denne boka oppsummerer ulike forelesningsnotater og undervisningsopplegg i anvendt kvantitativ analyse på ulike nivåer og spinner ut fra et ønske om å lage et hjelpemiddel og oppslagsverk for bachelor- og masterstudenter fra grunnleggende konsepter innen kvantitativ analyse til mer videregående temaer. Dette er en ambisiøs målsetning og det er mitt høyeste ønske at du som har startet på din akademiske vei på et bachelorstudium kan bruke denne boka gjennom flere metodeemner som omhandler kvantitativ dataanalyse, og bruke den - og nettressursene - som et hjelpemiddel og oppslagsverk framover. Temaene som tas opp i boka spenner derfor fra helt grunnleggende forhold til mer videregående teknikker. Det er selvsagt helt umulig å dekke alle deler av dette spennet svært detaljert - mange avveininger mellom bredde og dybde må gjøres.

Hensikten er altså å forsøke å formidle sentrale konsepter og teknikker i anvendt kvantitativ analyse, samt gjennom kodeblokkene med R-kode gi "oppskrift" på prosedyre slik at leseren kan reprodusere eksemplene. Jeg håper det kan tjene som et oppslagsverk og kanskje også som litt inspirasjon?

Det finnes mange veldig gode bøker som tar for seg introduksjon til og/eller videregående emner i kvantitativ analyse. Min gode kollega Christer Thranes bøker er eksempler på det. Det finnes også bøker som i hvert fall jeg tenker ikke er spesielt gode (i betydningen pedagogiske) i formidlingen (dette er selvsagt veldig subjektivt). Likvel - er det virkelig behov for enda flere, og er mitt bidrag nødvendigvis bedre/mer pedagogisk? Igjen - det får bli en subjektiv vurdering av leseren. Jeg har i hvert fall gjort et ærlig forsøk på å formidle dette stoffet på en måte jeg håper er forstålig etter å ha pløyd gjennom et utall bøker og andre ressurser. Jeg skal heller ikke legge skjul på at jeg ikke gjør anspråk på å revolusjonere noe som helst. Tvert i mot - jeg velger lett å bruke det jeg oppfatter som gode eksempler i ulike temaer fra andre. Sånn sett er mitt bidrag mer å samle gode gjennomganger og eksempler, vise leseren til hvor dette kommer fra slik at man kan gå til originalkilden om man ønsker, og formidle dette på et samlet sted, i norsk språkdrakt (men med mange engelske begreper...), på en forhåpentligvis forståelig og reproduserbar måte.

Samtidig er det åpenbart slik at det kan være krøkkete formuleringer, dårlige forklaringer, ulne beskrivelser, dårlige eksempler, for lite av noe, for mye av annet osv. Alle innspill og tilbakemeldinger mottas med stor takk (helt sant!).

Jeg har latt meg inspirere av mange kilder, som er gjengitt der de bør i teksten. Samtidig er det på sin plass å uttrykke en særlig takknemlighet til min gode kollega Professor Christer Thrane ved Høgskolen i Innlandet for motivasjon, inspirasjon og gode faglige samtaler.

## Programvare {.unnumbered}

Boka er skrevet med bruk av R [@rcoreteamLanguageEnvironmentStatistical2021] og RStudio [@rstudioteamRStudioIntegratedDevelopment2022]. R er en velkjent programvare innenfor statistikk, dataanalyse, datamodellering osv. R har noen store fordeler; det er gratis, det kjører på "alle" operativsystemer, og det har et svært stort bruker- og utviklermiljø som i all hovedsak deler alt gratis. Det er også enkelt å finne løsninger på det meste gjennom veiledninger og brukerforum på nett. Selve R er et programmeringsspråk og utviklermiljø for statistikk som gir en kjernefunksjonalitet innenfor datahåndtering, kalkulasjoner, dataanalyse, datamodellering, grafisk framstilling av data o.l.

R kommer med 14 basis "pakker". Det store potensialet ligger imidlertid i at brukerne av R utvikler tilleggspakker som man bruker i R. I arkivet CRAN (Comprehensive R Archive Network) finnes det `r nrow(available.packages(repos = "http://cran.us.r-project.org"))` da denne siden ble oppdatert sist. Alle pakkene tilbyr ulike tilrettelagte løsninger for ulike problemer/analyser. For "vanlige" analyser finner du veldig ofte flere pakker som løser samme problemer. Det er liten grunn til å legge skjul på at forfatteren av denne boka er svært begeistret for R og de mulighetene som finnes der. Samtidig er det også slik at det finnes flere gode alternativer, som vi kommer tilbake til i boka, for de som absolutt ikke vil bevege seg vekk fra "klikk og pek" programmer. Ethvert klikk og pek program må imidlertid ofre muligheter og fleksibilitet for grafisk brukervennlighet. I det store og det hele mener jeg det ikke er noen uoverkommelige grunner til å ikke bruke R fra start til slutt - såfremt man ofrer bare litt tid helt i starten til å komme over dørstokken.

Den største ulempen med R er at brukergrensesnittet er veldig ulikt hva vi kjenner fra Microsoft Office-typen brukergrensesnitt ("klikk og pek"), så det vil ta litt tid å bli kjent med programmet. Brukergrensesnittet er i all hovedsak kodebasert og ikke menybasert (med non unntak når vi f.eks. bruker RStudio), og det kan (dessverre) virke avskrekkende. Likevel, det er et utrolig kraftig verktøy hvis man tar seg tid til å lære seg det grunnleggende.

Brukere av boka vil kanskje bruke programvare som enten SPSS eller Stata. Konsepter og eksempler i notatet er som sagt laget og kjørt i R. Data og kodingen som er brukt er nesten uten unntak tilgjengelig slik at du kan reprodusere eksemplene og bruke kodingen på andre eksempler.

Det på sin plass å nevne alternativer til store og dyre programvarepakker som SPSS og Stata som mer og mer framstår som reelle og gode alternativer. To av disse, [jamovi](https://www.jamovi.org/) og [JASP](https://jasp-stats.org/), har sterkt voksende bruk (også i akademia) rundt om i verden. Et tredje tilsvarende alternativ er [Blue Sky Statistics](https://www.blueskystatistics.com/Default.asp). Dette er grafisk tiltalende og funksjonsrike statistikkpakker som alle kjører med R i bakgrunnen (alle analyser i jamovi, JASP og Blue Sky Statistics bruker R), og som også kan inkludere R kode direkte (i litt varierende grad og brukervennlighet). Det gjør at man *i utgangspunktet* kan utnytte pakkene skrevet for R direkte i de grafiske brukergrensesnitt, men hvordan disse programmene gjør dette varierer og også hvor direkte lett det er. I tillegg kan man (igjen i varierende grad mellom de to) hente ut R-kode fra analyser man gjør gjennom det grafiske brukergrensesnittet - noe som kan gjøre en overgang/introduksjon til R lettere om man vil den veien. Her vil jeg imidlertid poengtere at den beste måten å virkelig lære og bruke R er å lære og bruke R dirkete og ikke gjennom et grafisk brukergrensesnitt. Er du imidlertid overhodet ikke interessert i å bruke tid på R kommer du likevel veldig, veldig langt med det grafiske brukergrensesnittene nevnt i dette avsnittet. 

Leseren står selvsagt fritt til å hoppe elegant over alle verktøy som ikke er interessante. Det er klare fordeler og ulemper med alle, men forhåpentligvis vil de fleste finne et verktøy de kan bruke i utvalget vi har tatt med.

Der det er naturlig er kodingen inkludert slik at eksempler skal kunne replikeres av leseren. Jeg tror at man lærer R best gjennom bare å begynne. Man trenger ikke et langt grunnkurs i R for å gjøre enkle kvantitative analyser. Bare begynn! Repliser analyser i denne boka, så kommer du gradvis inn i hvordan R funker. Dette er ikke en bok om programmering i R, men en bok om praktisk bruk av R. Likevel har jeg med et par kapitler helt til slutt som tar for seg nedlasting, installasjon og grunnnleggende bruk. Det er også inkludert noen praktiske "tips & triks" på ting som kan være greit å lære seg eller ha som opplagsverk gjennom arbeidet. Kodingen er gjengitt fortløpende der analysen er gjort. Kodeblokkene skrus enkelt på (og av) ved hver analyse, graf osv gjennom en liten nedtrekksknapp ("Code"). Hvis du ikke er interessert i koden slipper du å se den, men den er altså tilgjengelig for deg. Hensikten er at analysene blir reproduserbare for leseren.

Jeg har brukt [R](https://www.r-project.org/), [RStudio](https://posit.co/products/open-source/rstudio/) og [Quarto](https://quarto.org/). R laster du ned og forholder deg siden ikke til annet enn at det kjører i bakgrunnen når du bruker RStudio (som altså er grensesnittet/programmet vi bruker). R baserer seg som sagt på bruk av ulike "pakker" som er utviklet av forskjellige utviklere og som er fritt tilgjengelig. Mange av disse har også datasett inkludert slik at det er enkelt å replikere eksempler. Så langt det er mulig har jeg som sagt basert meg på at det vi viser som eksempler skal være replikerbare for leseren.

En ting man lærer seg ved å begynne å bruke R er at det ofte finnes mange måter å gjøre samme ting på. Flere pakker tilbyr samme analyser som kanskje også "Base R" også gjør, med litt forskjellig output (eller i hvert fall design på output). Det er ganske sikkert (helt sikkert kan jeg vel si) at erfarne R-brukere/programmerere vil finne tungvinte måter ting gjøres på i denne boka. Jeg har ikke lagt vekt på å være ekstremt konsistent - kanskje har vi to steder brukt to ulike måter å få fram samme ting på. Selv om dette kanskje kan forvirre en leser håper vi samtidig det kan illustrere mulighetene - og hovedpoenget, mener vi, er å få fram gode analyser som kan hjelpe oss med å svare på en problemstillinge og gi oss innsikt og forståelse av det vi ønsker å skjønne mer av. Siden dette ikke er en lærebok i R, men i anvendt kvantitativ analyse, har vi latt det være utgangspunktet.

Jeg har lite fokus på matematikk og formler i den forstand at jeg mange steder ikke utleder i dybden forklaring på ulike analyser. Jeg tror det er fullt mulig å ha en praktisk forståelse og anvendt bruk av kvantitative analyser uten å ha dyptgående kjennskap til de matematiske eller statistiske forklaringene. Likevel, det er heller ikke slik at vi absolutt skal unngå dette. Jeg har derfor inkludert noe bakgrunnskunnskap og mer detaljerte forklaringer for å skape en ramme rundt analysene der jeg tenker det kan være interessant for de som ønsker å fordype seg noe mer. Mange vil kanskje velge å hoppe lett over det mer tekniske og matematiske. Det er på mange måter helt greit, men samtidig tilbyr jeg også noe mer redegjørelse for ulike konsepter.

```{r echo = FALSE}
library(report)
report(sessionInfo())
```
